# Generated by Django 5.2 on 2025-08-05 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome da Clínica')),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
            },
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(max_length=255, verbose_name='Número da Guia')),
                ('nome_paciente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Paciente')),
                ('medico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Médico')),
                ('trabalhos', models.TextField(blank=True, null=True, verbose_name='Tipo(s) de Trabalho')),
                ('valor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor (€)')),
                ('mes', models.CharField(max_length=50, verbose_name='Mês')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guias_app.clinica', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Guia',
                'verbose_name_plural': 'Guias',
                'unique_together': {('numero_guia', 'clinica', 'mes', 'ano')},
            },
        ),
    ]
