# Generated by Django 5.2 on 2025-08-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Encerrada'),
        ),
    ]
